# -*- coding: utf-8 -*-
"""AI Emotion 6000.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vACQFGjDkAcDfo_-SGiR1YFROt7skI4v
"""

# BLOCK 1: SETUP & DATA LOADING
# Install stats libraries
!pip install -q scipy statsmodels scikit-learn seaborn matplotlib pandas

# Mount Drive & load results
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np

# Load your 6,000-row dataset from your specified folder
csv_path = "/content/drive/MyDrive/AI Psychology Research/emotion_results_6000.csv"
df = pd.read_csv(csv_path)

print(f" ✅ Loaded {len(df)} rows | Columns: {len(df.columns)}")
print(f"Emotions detected: {df['Ground_Truth_Emotion'].unique().tolist()}")
print(f"Demographic Races: {df['Race'].unique().tolist()}")
print(f"Demographic Genders: {df['Gender'].unique().tolist()}")

# BLOCK 2: PER-EMOTION ACCURACY WITH CONFIDENCE INTERVALS
from scipy.stats import binomtest

# Calculate accuracy per emotion for MME Score (original context only)
results = []
for emotion in df['Ground_Truth_Emotion'].unique():
    subset = df[df['Ground_Truth_Emotion'] == emotion]
    correct = subset['MME_Score'].sum()
    total = len(subset)
    acc = correct / total

    # Exact binomial CI (Clopper-Pearson)
    bt = binomtest(correct, total, alternative='two-sided')
    ci_low, ci_high = bt.proportion_ci(confidence_level=0.95)

    results.append({
        'Emotion': emotion.capitalize(),
        'Correct': int(correct),
        'Total': total,
        'Accuracy (%)': round(acc * 100, 1),
        '95% CI Lower': round(ci_low * 100, 1),
        '95% CI Upper': round(ci_high * 100, 1)
    })

results_df = pd.DataFrame(results).sort_values('Accuracy (%)', ascending=False)
print("\n 📊 PER-EMOTION ACCURACY (Model Majority Ensemble)")
print("="*70)
print(results_df.to_string(index=False))
print("="*70)

# Save computed dataset metrics to Drive
results_df.to_csv("/content/drive/MyDrive/AI Psychology Research/Results 6000/per_emotion_accuracy_6000.csv", index=False)
print("\n ✅ Saved metrics file: per_emotion_accuracy_6000.csv")

# BLOCK 3: VISUALIZATION OF PER-EMOTION ACCURACY (BAR CHART & DATA TABLE)
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# 1. Verify directory path and sort data frames
output_dir = "/content/drive/MyDrive/AI Psychology Research/Results 6000/"
os.makedirs(output_dir, exist_ok=True)

# Sort data fields for chart alignment (worst to best)
plot_df = results_df.sort_values('Accuracy (%)', ascending=True).reset_index(drop=True)

# -------------------------------------------------------------------------
# IMAGE 1: WHITE-THEMED HORIZONTAL BAR CHART
# -------------------------------------------------------------------------
fig, ax = plt.subplots(figsize=(10, 6.2), dpi=1000)
colors = plt.cm.RdYlGn(plot_df['Accuracy (%)'] / 100)

y_pos = np.arange(len(plot_df))
accuracies = plot_df['Accuracy (%)'].values
errors = np.array([
    accuracies - plot_df['95% CI Lower'].values,
    plot_df['95% CI Upper'].values - accuracies
])

# FIXED: Changed bar borders to a subtle gray for contrast against the white background
bars = ax.barh(y_pos, accuracies, xerr=errors, color=colors,
                edgecolor='#7f8c8d', linewidth=1.2, capsize=7,
                error_kw={'elinewidth': 2.2, 'capthick': 2.2, 'ecolor': '#2c3e50', 'alpha': 0.95})

# Aesthetic layout configurations
ax.set_yticks(y_pos)
ax.set_yticklabels(plot_df['Emotion'], fontsize=13, color='#2c3e50', fontweight='bold')
ax.set_xlabel('Accuracy (%)', fontsize=14, fontweight='bold', color='#2c3e50', labelpad=12)
ax.set_title('Per-Emotion Accuracy: Model Majority Ensemble',
             fontsize=15, fontweight='bold', color='#2c3e50', pad=16)
ax.set_xlim(-3, 103)

# FIXED: Standard clean grid and white background configurations
ax.grid(axis='x', linestyle='--', alpha=0.4, color='#bdc3c7')
ax.set_facecolor('white')
fig.patch.set_facecolor('white')

# Clean borders
for spine in ax.spines.values():
    spine.set_color('#bdc3c7')
ax.tick_params(colors='#2c3e50', labelcolor='#2c3e50', labelsize=11)

# Apply dynamic text annotations next to bars
for i, (acc, y) in enumerate(zip(accuracies, y_pos)):
    y_offset = -0.25
    if acc == 100:
        ax.text(acc - 2, y + y_offset, f'{acc:.0f}%', va='center', ha='right', fontsize=10, fontweight='bold', color='white')
    elif acc > 40:
        ax.text(acc + 1.5, y + y_offset, f'{acc:.0f}%', va='center', ha='left', fontsize=10, fontweight='bold', color='#2c3e50')
    else:
        ax.text(acc + 1.5, y + y_offset, f'{acc:.0f}%', va='center', ha='left', fontsize=10, fontweight='bold', color='#2c3e50')

ax.text(0.98, 0.015, '95% Clopper-Pearson Confidence Intervals',
        transform=ax.transAxes, ha='right', va='bottom',
        fontsize=10, color='#7f8c8d', style='italic',
        bbox=dict(boxstyle='round,pad=0.45', facecolor='#f8f9fa', edgecolor='#bdc3c7', alpha=0.92))

plt.tight_layout()
chart_save_path = os.path.join(output_dir, "per_emotion_accuracy_6000.png")
plt.savefig(chart_save_path, dpi=1000, bbox_inches='tight', facecolor=fig.get_facecolor())
print(f" ✅ Chart image exported at 1000 DPI: {chart_save_path}")
plt.show()

# -------------------------------------------------------------------------
# IMAGE 2: PUBLICATION-READY DATA TABLE VISUALIZATION
# -------------------------------------------------------------------------
# Prepare data ordered cleanly from highest performing to lowest
table_df = results_df.sort_values('Accuracy (%)', ascending=False).copy()

fig_tab, ax_tab = plt.subplots(figsize=(10, 4), dpi=1000)
ax_tab.axis('off')
ax_tab.axis('tight')

# Convert data into matrix array strings for formatting presentation grid
table_data = table_df.values.tolist()
column_headers = table_df.columns.tolist()

# Construct standard table graphics container
table_obj = ax_tab.table(cellText=table_data, colLabels=column_headers, loc='center', cellLoc='center')

# Polish matrix cells visual formatting layout engine
table_obj.auto_set_font_size(False)
table_obj.set_fontsize(11)
table_obj.scale(1.2, 1.8)  # Expand padding cell margins cleanly

# Apply header block backgrounds vs row indices colors
for (row, col), cell in table_obj.get_celld().items():
    if row == 0:
        cell.set_text_props(weight='bold', color='white')
        cell.set_facecolor('#2c3e50')  # Dark blue header background
    else:
        cell.set_facecolor('#f8f9fa' if row % 2 == 0 else 'white')  # Zebra striping rows

plt.title('Statistical Distribution Performance Data Summary Matrix', fontsize=13, fontweight='bold', pad=10)
plt.tight_layout()

table_save_path = os.path.join(output_dir, "per_emotion_accuracy_table_6000.png")
plt.savefig(table_save_path, dpi=1000, bbox_inches='tight', facecolor='white')
print(f" ✅ Table image exported at 1000 DPI: {table_save_path}")
plt.show()

# BLOCK 4: MCNEMAR'S EXACT TEST (Model Comparisons)
from statsmodels.stats.contingency_tables import mcnemar

models = ['Qwen', 'Phi', 'Idefics']
comparisons = []

for i in range(len(models)):
    for j in range(i+1, len(models)):
        model_a = f"{models[i]}_Accuracy"
        model_b = f"{models[j]}_Accuracy"

        # Build standard 2x2 contingency matrix
        both_correct = ((df[model_a] == 1) & (df[model_b] == 1)).sum()
        a_correct_b_wrong = ((df[model_a] == 1) & (df[model_b] == 0)).sum()
        a_wrong_b_correct = ((df[model_a] == 0) & (df[model_b] == 1)).sum()
        both_wrong = ((df[model_a] == 0) & (df[model_b] == 0)).sum()

        table = [[both_correct, a_correct_b_wrong],
                 [a_wrong_b_correct, both_wrong]]

        # Perform calculation
        result = mcnemar(table, exact=True)

        comparisons.append({
            'Model A': models[i],
            'Model B': models[j],
            'Model A Correct': int(both_correct + a_correct_b_wrong),
            'Model B Correct': int(both_correct + a_wrong_b_correct),
            'p-value': result.pvalue,
            'Significant (α=0.05)': 'Yes' if result.pvalue < 0.05 else 'No'
        })

comp_df = pd.DataFrame(comparisons)
print("\n 🔍 MCNEMAR'S EXACT TEST (Paired Model Accuracy)")
print("="*70)
print(comp_df.to_string(index=False))
print("="*70)

comp_df.to_csv("/content/drive/MyDrive/AI Psychology Research/Results 6000/mcnemar_tests_6000.csv", index=False)
print("\n ✅ Saved results: mcnemar_tests_6000.csv")

# BLOCK 5: VISUALIZATION OF MCNEMAR PAIRWISE ACCURACY (BAR CHART & DATA TABLE)
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# 1. Verify directory path and load the dataset
output_dir = "/content/drive/MyDrive/AI Psychology Research/Results 6000/"
os.makedirs(output_dir, exist_ok=True)

csv_path = os.path.join(output_dir, "mcnemar_tests_6000.csv")
mcnemar_df = pd.read_csv(csv_path)

# -------------------------------------------------------------------------
# IMAGE 1: MCNEMAR PAIRWISE BAR CHART (1000 DPI)
# -------------------------------------------------------------------------
fig, ax = plt.subplots(figsize=(8, 5), dpi=1000)
model_colors = {'Qwen': '#1f77b4', 'Phi': '#ff7f0e', 'Idefics': '#2ca02c'}

x = np.arange(len(mcnemar_df))
width = 0.38

for idx, row in mcnemar_df.iterrows():
    ax.bar(x[idx] - width/2, row['Model A Correct'], width, color=model_colors[row['Model A']], edgecolor='black', linewidth=1.2)
    ax.bar(x[idx] + width/2, row['Model B Correct'], width, color=model_colors[row['Model B']], edgecolor='black', linewidth=1.2)

    p_val = row['p-value']
    y_pos = max(row['Model A Correct'], row['Model B Correct']) * 1.01
    ax.text(x[idx], y_pos, f'p={p_val:.12f}', ha='center', va='bottom', fontsize=9, fontweight='bold',
            color='red' if p_val < 0.05 else 'gray')

ax.set_xticks(x)
ax.set_xticklabels([f"{row['Model A']}\nvs\n{row['Model B']}" for _, row in mcnemar_df.iterrows()], fontsize=11)
ax.set_ylabel('Total Correct Predictions', fontsize=12, fontweight='bold', labelpad=8)
ax.set_title("McNemar's Exact Test: Pairwise Model Accuracy Comparison", fontsize=13, fontweight='bold', pad=12)
ax.grid(axis='y', linestyle='--', alpha=0.3, color='gray')
ax.set_facecolor('white')
fig.patch.set_facecolor('white')

handles = [plt.Rectangle((0,0),1,1, color=color, edgecolor='black') for model, color in model_colors.items()]
ax.legend(handles, model_colors.keys(), loc='lower right', frameon=True, framealpha=0.95, edgecolor='gray', fontsize=9)

plt.tight_layout()
chart_save_path = os.path.join(output_dir, "mcnemar_comparison_6000.png")
plt.savefig(chart_save_path, dpi=1000, bbox_inches='tight', facecolor='white')
print(f" ✅ McNemar chart saved at 1000 DPI: {chart_save_path}")
plt.show()

# -------------------------------------------------------------------------
# IMAGE 2: MCNEMAR STATISTICAL TABLE VISUALIZATION WITH EXPANDED COLUMNS (1000 DPI)
# -------------------------------------------------------------------------
fig_tab, ax_tab = plt.subplots(figsize=(11, 3), dpi=1000)  # Width slightly increased for the wider columns
ax_tab.axis('off')
ax_tab.axis('tight')

# Convert dataframe data into matrix array strings for table generation
table_data = mcnemar_df.values.tolist()
column_headers = mcnemar_df.columns.tolist()

# Construct table container
table_obj = ax_tab.table(cellText=table_data, colLabels=column_headers, loc='center', cellLoc='center')

# Polish formatting styles
table_obj.auto_set_font_size(False)
table_obj.set_fontsize(11)
table_obj.scale(1.2, 2.0)  # Generous cell padding height for clarity

# Apply color styles and custom column widths to table cells
for (row, col), cell in table_obj.get_celld().items():
    if col in [4, 5]:
        cell.set_width(cell.get_width() * 1.3)

    if row == 0:
        cell.set_text_props(weight='bold', color='white')
        cell.set_facecolor('#2c3e50')  # Dark blue header
    else:
        cell.set_facecolor('#f8f9fa' if row % 2 == 0 else 'white')  # Alternating row colors

plt.title("McNemar's Exact Test Pairwise Statistics Matrix Summary", fontsize=13, fontweight='bold', pad=12)
plt.tight_layout()

table_save_path = os.path.join(output_dir, "mcnemar_tests_table_6000.png")
plt.savefig(table_save_path, dpi=1000, bbox_inches='tight', facecolor='white')
print(f" ✅ McNemar data table saved with 30% wider columns at 1000 DPI: {table_save_path}")
plt.show()

# BLOCK 6: FISHER'S EXACT TEST & DEMOGRAPHIC BIAS VISUALIZATION (CHART & DATA TABLE)
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import fisher_exact, binomtest

# 1. Verify directory path
output_dir = "/content/drive/MyDrive/AI Psychology Research/Results 6000/"
os.makedirs(output_dir, exist_ok=True)

bias_results = []
emotions = df['Ground_Truth_Emotion'].unique()
races = df['Race'].unique()
genders = df['Gender'].unique()

print("\n ⚖️ COMPUTING DEMOGRAPHIC BIAS ANALYSIS METRICS...")

# PART 1: Race Intersection Matrix
for emotion in emotions:
    for race in races:
        race_emotion = df[(df['Race'] == race) & (df['Ground_Truth_Emotion'] == emotion)]
        other_emotion = df[(df['Race'] != race) & (df['Ground_Truth_Emotion'] == emotion)]

        if len(race_emotion) < 2 or len(other_emotion) < 2:
            continue

        correct_race = race_emotion['MME_Score'].sum()
        total_race = len(race_emotion)
        correct_other = other_emotion['MME_Score'].sum()
        total_other = len(other_emotion)

        # Apply strict cross-contingency checks
        if min(correct_race, total_race - correct_race, correct_other, total_other - correct_other) == 0:
            overall_acc = (correct_race + correct_other) / (total_race + total_other)
            bt = binomtest(int(correct_race), int(total_race), overall_acc, alternative='two-sided')
            p_val = bt.pvalue
            test_type = "Binomial (Fisher skipped)"
        else:
            table = [[correct_race, total_race - correct_race],
                     [correct_other, total_other - correct_other]]
            _, p_val = fisher_exact(table, alternative='two-sided')
            test_type = "Fisher's Exact"

        bias_results.append({
            'Demographic': 'Race',
            'Group': race,
            'Emotion': emotion.capitalize(),
            'Group Accuracy (%)': round(correct_race / total_race * 100, 1),
            'Group Size': total_race,
            'Other Groups Accuracy (%)': round(correct_other / total_other * 100, 1),
            'p-value': round(p_val, 4),
            'Significant (α=0.05)': 'Yes' if p_val < 0.05 else 'No',
            'Test Type': test_type
        })

# PART 2: Gender Intersection Matrix
for emotion in emotions:
    for gender in genders:
        gender_emotion = df[(df['Gender'] == gender) & (df['Ground_Truth_Emotion'] == emotion)]
        other_emotion = df[(df['Gender'] != gender) & (df['Ground_Truth_Emotion'] == emotion)]

        correct_gender = gender_emotion['MME_Score'].sum()
        total_gender = len(gender_emotion)
        correct_other = other_emotion['MME_Score'].sum()
        total_other = len(other_emotion)

        table = [[correct_gender, total_gender - correct_gender],
                 [correct_other, total_other - correct_other]]
        _, p_val = fisher_exact(table, alternative='two-sided')

        bias_results.append({
            'Demographic': 'Gender',
            'Group': gender,
            'Emotion': emotion.capitalize(),
            'Group Accuracy (%)': round(correct_gender / total_gender * 100, 1),
            'Group Size': total_gender,
            'Other Groups Accuracy (%)': round(correct_other / total_other * 100, 1),
            'p-value': round(p_val, 4),
            'Significant (α=0.05)': 'Yes' if p_val < 0.05 else 'No',
            'Test Type': "Fisher's Exact"
        })

bias_df = pd.DataFrame(bias_results).sort_values(['Demographic', 'Emotion', 'Group'])
csv_save_path = os.path.join(output_dir, "demographic_bias_tests_6000.csv")
bias_df.to_csv(csv_save_path, index=False)
print(f" ✅ Computation complete! Saved: {csv_save_path}")

# -------------------------------------------------------------------------
# IMAGE 1: DEMOGRAPHIC BIAS ACCURACY COMPARISON CHART (1000 DPI)
# -------------------------------------------------------------------------
fig, axes = plt.subplots(2, 1, figsize=(12, 10), dpi=1000)
fig.patch.set_facecolor('white')

# Subplot 1: Race Performance Breakdown
race_df = bias_df[bias_df['Demographic'] == 'Race']
sns.barplot(data=race_df, x='Emotion', y='Group Accuracy (%)', hue='Group', ax=axes[0], palette='Set2', edgecolor='#7f8c8d', linewidth=1)
axes[0].set_title("Emotion Recognition Accuracy Across Racial Demographics", fontsize=13, fontweight='bold', color='#2c3e50', pad=10)
axes[0].set_ylabel("Group Accuracy (%)", fontsize=11, fontweight='bold', color='#2c3e50')
axes[0].set_xlabel("", fontsize=11)
axes[0].set_ylim(0, 105)
axes[0].grid(axis='y', linestyle='--', alpha=0.4, color='#bdc3c7')
axes[0].set_facecolor('white')
axes[0].legend(title='Racial Subgroup', loc='upper right', frameon=True, facecolor='white', edgecolor='#bdc3c7')

# Subplot 2: Gender Performance Breakdown
gender_df = bias_df[bias_df['Demographic'] == 'Gender']
sns.barplot(data=gender_df, x='Emotion', y='Group Accuracy (%)', hue='Group', ax=axes[1], palette='Pastel1', edgecolor='#7f8c8d', linewidth=1)
axes[1].set_title("Emotion Recognition Accuracy Across Gender Demographics", fontsize=13, fontweight='bold', color='#2c3e50', pad=10)
axes[1].set_ylabel("Group Accuracy (%)", fontsize=11, fontweight='bold', color='#2c3e50')
axes[1].set_xlabel("Emotion Category", fontsize=11, fontweight='bold', color='#2c3e50')
axes[1].set_ylim(0, 105)
axes[1].grid(axis='y', linestyle='--', alpha=0.4, color='#bdc3c7')
axes[1].set_facecolor('white')
axes[1].legend(title='Gender', loc='upper right', frameon=True, facecolor='white', edgecolor='#bdc3c7')

plt.tight_layout(pad=3.0)
chart_save_path = os.path.join(output_dir, "demographic_bias_chart_6000.png")
plt.savefig(chart_save_path, dpi=1000, bbox_inches='tight', facecolor='white')
print(f" ✅ Demographic bias chart saved at 1000 DPI: {chart_save_path}")
plt.show()

# -------------------------------------------------------------------------
# IMAGE 2: PUBLICATION-READY BIAS STATISTICS TABLE VISUALIZATION (1000 DPI)
# -------------------------------------------------------------------------
# Set up a proportional layout to fit the statistical data rows clearly
fig_tab, ax_tab = plt.subplots(figsize=(15, 14), dpi=1000)
ax_tab.axis('off')
ax_tab.axis('tight')

table_data = bias_df.values.tolist()
column_headers = bias_df.columns.tolist()

table_obj = ax_tab.table(cellText=table_data, colLabels=column_headers, loc='center', cellLoc='center')

table_obj.auto_set_font_size(False)
table_obj.set_fontsize(9)
table_obj.scale(1.0, 1.4)  # Tight padding scaling to comfortably fit rows on the canvas

# Expand column widths by 25% across long text descriptors to avoid cramped cells
for (row, col), cell in table_obj.get_celld().items():
    if col in [0, 2, 5, 7, 8]:  # Columns: Demographic, Emotion, Other Groups Accuracy, Significant, Test Type
        cell.set_width(cell.get_width() * 1.25)

    if row == 0:
        cell.set_text_props(weight='bold', color='white', fontsize=10)
        cell.set_facecolor('#2c3e50')  # Dark blue header block
    else:
        # Bold rows that show statistically significant bias markers
        if table_data[row-1][7] == 'Yes':
            cell.set_text_props(weight='bold', color='#e74c3c') # Red text highlight for significant bias
        cell.set_facecolor('#f8f9fa' if row % 2 == 0 else 'white')  # Zebra striping

plt.title("Demographic Intersectionality Performance & Bias Statistics Matrix", fontsize=14, fontweight='bold', pad=15, color='#2c3e50')
plt.tight_layout()

table_save_path = os.path.join(output_dir, "demographic_bias_table_6000.png")
plt.savefig(table_save_path, dpi=1000, bbox_inches='tight', facecolor='white')
print(f" ✅ Demographic bias statistics data table saved at 1000 DPI: {table_save_path}")
plt.show()

# BLOCK 7: VISUALIZATION OF DEMOGRAPHIC BIAS (HEATMAPS)
import seaborn as sns

bias_df = pd.read_csv("/content/drive/MyDrive/AI Psychology Research/Results 6000/demographic_bias_tests_6000.csv")
emotion_order = ['Anger', 'Disgust', 'Fear', 'Joy', 'Sadness', 'Surprise']

# Setup plotting structures for Race
race_df = bias_df[bias_df['Demographic'] == 'Race'].copy()
race_df['Emotion'] = pd.Categorical(race_df['Emotion'], categories=emotion_order, ordered=True)
race_df = race_df.sort_values('Emotion')
race_acc = race_df.pivot(index='Emotion', columns='Group', values='Group Accuracy (%)')
race_sig = race_df.pivot(index='Emotion', columns='Group', values='Significant (α=0.05)')
race_annot = race_acc.applymap(lambda x: f"{x:.0f}" if not pd.isna(x) else "")

for i in range(race_acc.shape[0]):
    for j in range(race_acc.shape[1]):
        if not pd.isna(race_sig.iloc[i, j]) and race_sig.iloc[i, j] == 'Yes':
            race_annot.iloc[i, j] += '*'

# Setup plotting structures for Gender
gender_df = bias_df[bias_df['Demographic'] == 'Gender'].copy()
gender_df['Emotion'] = pd.Categorical(gender_df['Emotion'], categories=emotion_order, ordered=True)
gender_df = gender_df.sort_values('Emotion')
gender_acc = gender_df.pivot(index='Emotion', columns='Group', values='Group Accuracy (%)')
gender_sig = gender_df.pivot(index='Emotion', columns='Group', values='Significant (α=0.05)')
gender_annot = gender_acc.applymap(lambda x: f"{x:.0f}" if not pd.isna(x) else "")

for i in range(gender_acc.shape[0]):
    for j in range(gender_acc.shape[1]):
        if not pd.isna(gender_sig.iloc[i, j]) and gender_sig.iloc[i, j] == 'Yes':
            gender_annot.iloc[i, j] += '*'

# Plot subplots side-by-side
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6.5), dpi=1000, gridspec_kw={'width_ratios': [5, 2]})

sns.heatmap(race_acc, annot=race_annot.values, fmt='', cmap='Blues', vmin=0, vmax=100, ax=ax1,
            cbar_kws={'label': 'Accuracy (%)', 'shrink': 0.8}, linewidths=0.8, linecolor='white', square=True,
            annot_kws={'size': 11, 'weight': 'bold'})
ax1.set_title('Race × Emotion Accuracy\n(* p<0.05 vs. other groups)', fontsize=13, fontweight='bold', pad=12)

sns.heatmap(gender_acc, annot=gender_annot.values, fmt='', cmap='Blues', vmin=0, vmax=100, ax=ax2,
            cbar=False, linewidths=0.8, linecolor='white', square=True, annot_kws={'size': 12, 'weight': 'bold'})
ax2.set_title('Gender × Emotion Accuracy\n(* p<0.05 vs. opposite group)', fontsize=13, fontweight='bold', pad=12)

fig.patch.set_facecolor('white')
plt.tight_layout()
save_heatmap_path = "/content/drive/MyDrive/AI Psychology Research/Results 6000/demographic_bias_heatmap_6000.png"
plt.savefig(save_heatmap_path, dpi=1000, bbox_inches='tight', facecolor='white')
print(f" ✅ Heatmap graphic saved successfully to: {save_heatmap_path}")
plt.show()

# BLOCK 8: CONTEXT SHIFT ANALYSIS
shift_results = []

for model in ['Qwen', 'Phi', 'Idefics']:
    shift_col = f"{model}_Context_Shift"
    total_shifts = df[shift_col].sum()
    total_images = len(df)
    shift_rate = total_shifts / total_images

    original_correct = df[f"{model}_Accuracy"] == 1
    model_lower = model.lower()
    black_correct = df[f"{model_lower}_black_predicted"] == df["Ground_Truth_Emotion"]

    harmful_shifts = ((original_correct) & (~black_correct)).sum()
    helpful_shifts = ((~original_correct) & (black_correct)).sum()

    shift_results.append({
        'Model': model,
        'Context Shifts': int(total_shifts),
        'Total Images': total_images,
        'Shift Rate (%)': round(shift_rate * 100, 1),
        'Harmful Shifts': int(harmful_shifts),
        'Helpful Shifts': int(helpful_shifts)
    })

shift_df = pd.DataFrame(shift_results)
print("\n 🔄 CONTEXT SHIFT ANALYSIS (Original vs. Black Background)")
print("="*70)
print(shift_df.to_string(index=False))
print("="*70)

shift_df.to_csv("/content/drive/MyDrive/AI Psychology Research/Results 6000/context_shift_analysis_6000.csv", index=False)
print("\n ✅ Saved data matrices: context_shift_analysis_6000.csv")

# BLOCK 9: VISUALIZATION OF CONTEXT SHIFT IMPLICATIONS (DIVERGING CHART & DATA TABLE)
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# 1. Verify directory path exists
output_dir = "/content/drive/MyDrive/AI Psychology Research/Results 6000/"
os.makedirs(output_dir, exist_ok=True)

# -------------------------------------------------------------------------
# IMAGE 1: DIVERGING CONTEXT SHIFT IMPACT BAR CHART (1000 DPI)
# -------------------------------------------------------------------------
fig, ax = plt.subplots(figsize=(10, 3.5), dpi=1000)

models = shift_df['Model'].values
harmful = shift_df['Harmful Shifts'].values
helpful = shift_df['Helpful Shifts'].values
shift_rates = shift_df['Shift Rate (%)'].values
y_pos = np.arange(len(models))

ax.barh(y_pos, -harmful, color='#e74c3c', edgecolor='black', linewidth=1.3, label='Harmful Shifts (Correct → Wrong)')
ax.barh(y_pos, helpful, color='#27ae60', edgecolor='black', linewidth=1.3, label='Helpful Shifts (Wrong → Correct)')
ax.axvline(x=0, color='black', linestyle='-', linewidth=1.8, alpha=0.7)

for i, (model, rate) in enumerate(zip(models, shift_rates)):
    ax.text(-5, i, f' {model}\n ({rate}%)', va='center', ha='right', fontsize=9.5, fontweight='bold', color='black')

ax.set_yticks([])
ax.set_xlabel('Shift Count Context Frequency', fontsize=13, fontweight='bold', labelpad=10)
ax.set_title('Context Shift Impact: Original → Black Background', fontsize=14, fontweight='bold', pad=15)
ax.legend(loc='lower left', frameon=True, framealpha=0.95, edgecolor='gray', fontsize=10)
ax.grid(axis='x', linestyle='--', alpha=0.3, color='gray')
ax.set_facecolor('white')
fig.patch.set_facecolor('white')

plt.tight_layout()
save_diverge_path = os.path.join(output_dir, "context_shift_diverging_6000.png")
plt.savefig(save_diverge_path, dpi=1000, bbox_inches='tight', facecolor='white')
print(f" ✅ Context shift chart rendered at 1000 DPI: {save_diverge_path}")
plt.show()

# -------------------------------------------------------------------------
# IMAGE 2: PUBLICATION-READY CONTEXT SHIFT DATA TABLE (1000 DPI)
# -------------------------------------------------------------------------
fig_tab, ax_tab = plt.subplots(figsize=(10, 3), dpi=1000)
ax_tab.axis('off')
ax_tab.axis('tight')

# Convert data into matrix array strings for layout generation
table_data = shift_df.values.tolist()
column_headers = shift_df.columns.tolist()

# Construct standard table graphics container
table_obj = ax_tab.table(cellText=table_data, colLabels=column_headers, loc='center', cellLoc='center')

# Polish matrix cells formatting layout configurations
table_obj.auto_set_font_size(False)
table_obj.set_fontsize(11)
table_obj.scale(1.2, 2.0)  # Expand row heights elegantly for presentation clarity

# Apply color design principles to headers vs alternating index rows
for (row, col), cell in table_obj.get_celld().items():
    if row == 0:
        cell.set_text_props(weight='bold', color='white')
        cell.set_facecolor('#2c3e50')  # Dark blue header block
    else:
        cell.set_facecolor('#f8f9fa' if row % 2 == 0 else 'white')  # Clean zebra striping

plt.title('Context Shift Robustness Metrics & Frequency Matrix Summary', fontsize=13, fontweight='bold', pad=12)
plt.tight_layout()

table_save_path = os.path.join(output_dir, "context_shift_table_6000.png")
plt.savefig(table_save_path, dpi=1000, bbox_inches='tight', facecolor='white')
print(f" ✅ Context shift data table saved at 1000 DPI: {table_save_path}")
plt.show()

# BLOCK 10: BRIER SCORE (Confidence Calibration)
from sklearn.metrics import brier_score_loss

brier_results = []
emotions_lower = ['joy', 'sadness', 'anger', 'fear', 'disgust', 'surprise']

for model in ['qwen', 'phi', 'idefics']:
    probs = []
    actuals = []

    for idx, row in df.iterrows():
        true_emotion = row['Ground_Truth_Emotion']
        prob_col = f"{model}_original_{true_emotion}"

        prob = row[prob_col] / 100.0
        probs.append(prob)
        actuals.append(1)

    brier = brier_score_loss(actuals, probs)
    brier_results.append({
        'Model': model.capitalize(),
        'Brier Score': round(brier, 3),
        'Interpretation': 'Well calibrated' if brier < 0.15 else 'Moderately calibrated' if brier < 0.25 else 'Poorly calibrated'
    })

brier_df = pd.DataFrame(brier_results)
print("\n 🎯 BRIER SCORE (Confidence Calibration)")
print("="*60)
print(brier_df.to_string(index=False))
print("="*60)

brier_df.to_csv("/content/drive/MyDrive/AI Psychology Research/Results 6000/brier_scores_6000.csv", index=False)
print(" ✅ Saved: brier_scores_6000.csv")

# BLOCK 11: VISUALIZATION OF BRIER SCORING CALIBRATION (BAR CHART & DATA TABLE)
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# 1. Verify directory path exists
output_dir = "/content/drive/MyDrive/AI Psychology Research/Results 6000/"
os.makedirs(output_dir, exist_ok=True)

# Sort ascending by score (best calibration to worst calibration)
brier_df = brier_df.sort_values('Brier Score', ascending=True).reset_index(drop=True)
models_b = brier_df['Model'].values
scores_b = brier_df['Brier Score'].values

# -------------------------------------------------------------------------
# IMAGE 1: BRIER SCORE HORIZONTAL BAR CHART (1000 DPI)
# -------------------------------------------------------------------------
fig, ax = plt.subplots(figsize=(9, 5), dpi=1000)
colors_b = ['#e74c3c' if s >= 0.25 else '#f39c12' if s >= 0.15 else '#27ae60' for s in scores_b]

y_pos = np.arange(len(models_b))
bars = ax.barh(y_pos, scores_b, color=colors_b, edgecolor='black', linewidth=1.5)

for i, score in enumerate(scores_b):
    ax.text(score + 0.012, i, f'{score:.3f}', va='center', ha='left', fontsize=12, fontweight='bold', color='black')

ax.axvline(x=0.15, color='#27ae60', linestyle='--', linewidth=2, alpha=0.7)
ax.axvline(x=0.25, color='#f39c12', linestyle='--', linewidth=2, alpha=0.7)

ax.set_yticks(y_pos)
ax.set_yticklabels(models_b, fontsize=13, fontweight='bold')
ax.set_xlabel('Brier Score (Lower = Better Calibration)', fontsize=13, fontweight='bold', labelpad=10)
ax.set_title('Model Confidence Calibration Threshold Matrix', fontsize=15, fontweight='bold', pad=15)
ax.set_xlim(0, max(scores_b) * 1.25)
ax.set_facecolor('white')
fig.patch.set_facecolor('white')

plt.tight_layout()
save_brier_path = os.path.join(output_dir, "brier_calibration_6000.png")
plt.savefig(save_brier_path, dpi=1000, bbox_inches='tight', facecolor='white')
print(f" ✅ Calibration chart outputted at 1000 DPI: {save_brier_path}")
plt.show()

# -------------------------------------------------------------------------
# IMAGE 2: PUBLICATION-READY BRIER CALIBRATION DATA TABLE (1000 DPI)
# -------------------------------------------------------------------------
fig_tab, ax_tab = plt.subplots(figsize=(9, 3), dpi=1000)
ax_tab.axis('off')
ax_tab.axis('tight')

# Convert dataframe data into matrix array strings for table generation
table_data = brier_df.values.tolist()
column_headers = brier_df.columns.tolist()

# Construct standard table graphics container
table_obj = ax_tab.table(cellText=table_data, colLabels=column_headers, loc='center', cellLoc='center')

# Polish matrix cells visual formatting layout configurations
table_obj.auto_set_font_size(False)
table_obj.set_fontsize(11)
table_obj.scale(1.2, 2.0)  # Expand cell padding heights for publication-ready spacing

# Apply visual formatting design to headers vs alternating index rows
for (row, col), cell in table_obj.get_celld().items():
    if row == 0:
        cell.set_text_props(weight='bold', color='white')
        cell.set_facecolor('#2c3e50')  # Dark blue header block
    else:
        cell.set_facecolor('#f8f9fa' if row % 2 == 0 else 'white')  # Clean zebra striping

plt.title('Brier Score Calibration Analysis Summary Matrix', fontsize=13, fontweight='bold', pad=12)
plt.tight_layout()

table_save_path = os.path.join(output_dir, "brier_calibration_table_6000.png")
plt.savefig(table_save_path, dpi=1000, bbox_inches='tight', facecolor='white')
print(f" ✅ Brier calibration data table saved at 1000 DPI: {table_save_path}")
plt.show()

# BLOCK 12: MULTICLASS CONFUSION MATRICES
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix

matrices_to_run = [
    ("Qwen2-VL", "qwen_original_predicted"),
    ("Phi-3.5-Vision", "phi_original_predicted"),
    ("Idefics2", "idefics_original_predicted")
]

labels_list = ['joy', 'sadness', 'anger', 'fear', 'disgust', 'surprise']
labels_display = ['Joy', 'Sadness', 'Anger', 'Fear', 'Disgust', 'Surprise']

for title, column_key in matrices_to_run:
    # Set to 1000 DPI as requested
    plt.figure(figsize=(8, 6), dpi=1000)
    cm = confusion_matrix(df['Ground_Truth_Emotion'], df[column_key], labels=labels_list)

    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=labels_display, yticklabels=labels_display,
                linewidths=0.5, linecolor='white', cbar=True)

    plt.title(f'Confusion Matrix: {title} (Original Context)', fontsize=13, fontweight='bold', pad=15)
    plt.xlabel('Predicted Label Target', fontsize=11, fontweight='medium')
    plt.ylabel('Ground Truth Target', fontsize=11, fontweight='medium')

    # FIXED: Removed .astype(str) since title is already a string
    clean_title = title.replace('.', '_')
    matrix_save_path = f"/content/drive/MyDrive/AI Psychology Research/Results 6000/confusion_matrix_{clean_title}_6000.png"

    # Ensured the figure saves at 1000 DPI
    plt.savefig(matrix_save_path, dpi=1000, bbox_inches='tight')
    print(f" ✅ Generated matrix path: {matrix_save_path}")
    plt.show()

# BLOCK 13: EQUAL OPPORTUNITY DIFFERENCE & FAIRNESS LADDER VISUALIZATION (CHART & DATA TABLE)
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D

# 1. Ensure output directory structure exists
output_dir = "/content/drive/MyDrive/AI Psychology Research/Results 6000/"
os.makedirs(output_dir, exist_ok=True)

# 2. Calculate True Positive Rate (TPR) per group
fairness_data = []
for emotion in df['Ground_Truth_Emotion'].unique():
    for race in df['Race'].unique():
        subset = df[(df['Ground_Truth_Emotion'] == emotion) & (df['Race'] == race)]
        if len(subset) == 0:
            continue
        tpr = subset['MME_Score'].mean() * 100
        fairness_data.append({
            'Emotion': emotion.capitalize(),
            'Race': race,
            'TPR (%)': round(tpr, 1),
            'Group Size': len(subset)
        })

fair_df = pd.DataFrame(fairness_data)

# 3. Calculate metrics per emotion matching your specific classification array
emotion_order = ['joy', 'sadness', 'anger', 'fear', 'disgust', 'surprise']
fairness_metrics = []

for emotion in sorted(df['Ground_Truth_Emotion'].unique(), key=lambda x: emotion_order.index(x)):
    emotion_data = fair_df[fair_df['Emotion'] == emotion.capitalize()]
    if len(emotion_data) < 2:
        continue

    tprs = emotion_data['TPR (%)'].values
    fairness_metrics.append({
        'Emotion': emotion.capitalize(),
        'Mean TPR (%)': round(np.mean(tprs), 1),
        'Std Dev TPR (%)': round(np.std(tprs, ddof=1), 1),
        'Min TPR (%)': round(np.min(tprs), 1),
        'Max TPR (%)': round(np.max(tprs), 1),
        'Max TPR Diff (%)': round(np.max(tprs) - np.min(tprs), 1),
        'Races with 0% TPR': int(np.sum(tprs == 0))
    })

metrics_df = pd.DataFrame(fairness_metrics)

print("\n⚖️ FAIRNESS METRICS BY EMOTION (Descriptive Statistics)")
print("="*70)
print(metrics_df.to_string(index=False))
print("="*70)

# Save metrics tracking CSV to updated target folder path
metrics_save_csv = os.path.join(output_dir, "fairness_metrics.csv")
metrics_df.to_csv(metrics_save_csv, index=False)
print(f"\n✅ Saved CSV: {metrics_save_csv}")

# 4. Initialize Visual Ladder Rendering
# Sort by disparity (worst to best performance) for visual ladder alignment
ladder_df = metrics_df.sort_values('Max TPR Diff (%)', ascending=False).reset_index(drop=True)
emotions = ladder_df['Emotion'].values
min_tpr = ladder_df['Min TPR (%)'].values
max_tpr = ladder_df['Max TPR (%)'].values
mean_tpr = ladder_df['Mean TPR (%)'].values
zero_races = ladder_df['Races with 0% TPR'].values
disparity = ladder_df['Max TPR Diff (%)'].values

# -------------------------------------------------------------------------
# IMAGE 1: FAIRNESS LADDER RANGE CHART (1000 DPI)
# -------------------------------------------------------------------------
fig, ax = plt.subplots(figsize=(12.5, 6.5), dpi=1000)
y_pos = np.arange(len(emotions))

# Map red-to-green palette inverse scaling properties
norm = plt.Normalize(disparity.min(), disparity.max())
colors = plt.cm.RdYlGn_r(norm(disparity))

# Draw horizontal range structures
for i, (mn, mx, mean, color, zeros) in enumerate(zip(min_tpr, max_tpr, mean_tpr, colors, zero_races)):
    if mx - mn > 0.5:
        ax.plot([mn, mx], [i, i],
                color=color,
                linewidth=8.5,
                solid_capstyle='round',
                alpha=0.95,
                zorder=2)

    # Plot statistical mean positions
    ax.scatter(mean, i,
               s=280,
               color='white',
               edgecolors='#34495e',
               linewidths=2.2,
               zorder=3)

    # Plot critical zero marker locations if flag constraints match
    if zeros > 0:
        ax.scatter(0, i,
                   s=320,
                   marker='x',
                   color='#e74c3c',
                   linewidths=2.5,
                   zorder=4)

# Apply descriptive textual alignment strings to row indexes
for i, (emotion, diff, zeros) in enumerate(zip(emotions, disparity, zero_races)):
    label = f"{emotion} ({diff:.1f}% gap)"
    if zeros > 0:
        label += f"\n {zeros} race(s) at 0%"
    ax.text(-12.5, i, label,
            ha='right',
            va='center',
            fontsize=12.5,
            fontweight='bold',
            color='#2c3e50')

# Apply styling configurations to standard axes elements
ax.set_yticks([])
ax.set_xlabel('True Positive Rate (TPR) by Race Group (%)', fontsize=13, fontweight='bold', labelpad=14)
ax.set_title('Fairness Ladder: Racial Disparity in Emotion Recognition\n(Longer bars = greater unfairness)',
             fontsize=15, fontweight='bold', pad=20)
ax.set_xlim(-12, 102)
ax.set_ylim(-0.8, len(emotions) - 0.2)
ax.grid(axis='x', linestyle='--', alpha=0.35, color='#bdc3c7', linewidth=1.2)
ax.set_facecolor('white')
fig.patch.set_facecolor('white')

# Render dynamic reference boundaries mapping absolute equity targets
ax.axvline(x=100, color='#27ae60', linestyle='--', linewidth=2.2, alpha=0.85)
ax.text(92, len(emotions)-0.3, '\n\n\n\nPerfect\nfairness',
        ha='left', va='top', fontsize=10.5, color='#27ae60', fontweight='bold')

# Configure Legend
legend_elements = [
    Line2D([0], [0],
           marker='o',
           color='w',
           label='Mean TPR',
           markerfacecolor='white',
           markeredgecolor='#34495e',
           markersize=11,
           markeredgewidth=2.2),
    Line2D([0], [0],
           marker='x',
           color='w',
           label='Race group(s) with 0% TPR',
           markerfacecolor='#e74c3c',
           markeredgecolor='black',
           markersize=12,
           markeredgewidth=2.5)
]
ax.legend(handles=legend_elements,
          loc='upper left',
          frameon=True,
          framealpha=0.92,
          edgecolor='#ecf0f1',
          fontsize=10.5,
          handletextpad=0.5,
          borderpad=0.8)

# Lower context box metrics descriptions
fig.text(0.5, 0.018,
         'Interpretation: Horizontal bar length = max racial disparity for that emotion\n'
         'Critical concern: Emotions with races at 0% TPR represent complete failure for demographic subgroups',
         ha='center', va='bottom', fontsize=10, color='#7f8c8d', style='italic',
         bbox=dict(boxstyle='round,pad=0.55', facecolor='white', edgecolor='#ecf0f1', alpha=0.95))

plt.tight_layout(rect=[0, 0.07, 1, 0.95])

image_save_path = os.path.join(output_dir, "fairness_ladder_sophisticated.png")
plt.savefig(image_save_path, dpi=1000, bbox_inches='tight', facecolor='white')
print(f"✅ Sophisticated fairness visualization saved at 1000 DPI: {image_save_path}")
plt.show()

# -------------------------------------------------------------------------
# IMAGE 2: PUBLICATION-READY DESCRIPTIVE FAIRNESS METRICS TABLE (1000 DPI)
# -------------------------------------------------------------------------
fig_tab, ax_tab = plt.subplots(figsize=(11, 4), dpi=1000)
ax_tab.axis('off')
ax_tab.axis('tight')

# Convert metrics data matrix into clean strings for visual framing
table_data = metrics_df.values.tolist()
column_headers = metrics_df.columns.tolist()

# Construct standard table graphics container
table_obj = ax_tab.table(cellText=table_data, colLabels=column_headers, loc='center', cellLoc='center')

# Polish matrix cells visual formatting layout engines
table_obj.auto_set_font_size(False)
table_obj.set_fontsize(11)
table_obj.scale(1.1, 1.9)  # Expand padding heights comfortably for publication clear spacing

# Apply uniform column broadening engine across long metrics headers to prevent truncation
for (row, col), cell in table_obj.get_celld().items():
    if col in [1, 2, 5, 6]:  # Target descriptive columns with longer character lengths
        cell.set_width(cell.get_width() * 1.2)

    if row == 0:
        cell.set_text_props(weight='bold', color='white')
        cell.set_facecolor('#2c3e50')  # Solid signature header block
    else:
        # Subtle font color alteration highlighting critical zero-bound demographic dropouts
        if int(table_data[row-1][6]) > 0:
            cell.set_text_props(weight='bold', color='#e74c3c')
        cell.set_facecolor('#f8f9fa' if row % 2 == 0 else 'white')  # Soft alternating zebra striping

plt.title('Equal Opportunity Disparity & Fairness Performance Distribution Matrix', fontsize=13, fontweight='bold', pad=12, color='#2c3e50')
plt.tight_layout()

table_save_path = os.path.join(output_dir, "fairness_metrics_table_6000.png")
plt.savefig(table_save_path, dpi=1000, bbox_inches='tight', facecolor='white')
print(f"✅ Fairness metrics statistical table saved at 1000 DPI: {table_save_path}")
plt.show()

# BLOCK 14: GENERATION & VISUALIZATION OF THE COMPREHENSIVE MASTER RESULTS MATRIX
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# 1. Verify directory path exists
output_dir = "/content/drive/MyDrive/AI Psychology Research/Results 6000/"
os.makedirs(output_dir, exist_ok=True)

# 2. Define standard ordering for structured presentation
emotion_order = ['Joy', 'Sadness', 'Anger', 'Fear', 'Disgust', 'Surprise']
emotions_lower = [e.lower() for e in emotion_order]

master_rows = []

# --- PART 1: INDIVIDUAL MODEL PERFORMANCE BY BACKGROUND ---
model_mapping = {
    'qwen': 'Qwen2-VL-2B-Instruct',
    'phi': 'Phi-3.5-vision-instruct',
    'idefics': 'Idefics2-8b'
}
backgrounds = ['original', 'black']

for model_key, model_name in model_mapping.items():
    for bg in backgrounds:
        row_data = {
            'Evaluation Layer': 'Individual Model',
            'Architecture / Method': model_name,
            'Background Context': bg.capitalize()
        }

        # Calculate accuracy per emotion
        for e_low, e_cap in zip(emotions_lower, emotion_order):
            subset = df[df['Ground_Truth_Emotion'] == e_low]
            pred_col = f"{model_key}_{bg}_predicted"

            correct = (subset[pred_col] == e_low).sum()
            total = len(subset)
            acc_pct = (correct / total) * 100 if total > 0 else 0.0
            row_data[f"{e_cap} (%)"] = round(acc_pct, 1)

        # Calculate overall macro-average across all 7 emotions for this subset
        all_correct = (df[f"{model_key}_{bg}_predicted"] == df['Ground_Truth_Emotion']).sum()
        all_total = len(df)
        row_data['Macro Average (%)'] = round((all_correct / all_total) * 100, 1) if all_total > 0 else 0.0
        master_rows.append(row_data)

# --- PART 2: CONTEXT-SPECIFIC GLOBAL PERFORMANCE (AVERAGED) ---
for bg in backgrounds:
    row_data = {
        'Evaluation Layer': 'Context Average',
        'Architecture / Method': f'All Models Combined ({bg.capitalize()})',
        'Background Context': bg.capitalize()
    }

    for e_low, e_cap in zip(emotions_lower, emotion_order):
        accs = []
        for model_key in model_mapping.keys():
            subset = df[df['Ground_Truth_Emotion'] == e_low]
            pred_col = f"{model_key}_{bg}_predicted"
            correct = (subset[pred_col] == e_low).sum()
            total = len(subset)
            accs.append((correct / total) * 100 if total > 0 else 0.0)
        row_data[f"{e_cap} (%)"] = round(np.mean(accs), 1)

    global_accs = []
    for model_key in model_mapping.keys():
        correct = (df[f"{model_key}_{bg}_predicted"] == df['Ground_Truth_Emotion']).sum()
        global_accs.append((correct / len(df)) * 100 if len(df) > 0 else 0.0)
    row_data['Macro Average (%)'] = round(np.mean(global_accs), 1)
    master_rows.append(row_data)

# --- PART 3: MODEL MAJORITY ENSEMBLE (MME) PERFORMANCE ---
mme_row = {
    'Evaluation Layer': 'Ensemble System',
    'Architecture / Method': 'Model Majority Ensemble (MME)',
    'Background Context': 'Original'
}

for e_low, e_cap in zip(emotions_lower, emotion_order):
    subset = df[df['Ground_Truth_Emotion'] == e_low]
    correct = subset['MME_Score'].sum()
    total = len(subset)
    mme_row[f"{e_cap} (%)"] = round((correct / total) * 100, 1) if total > 0 else 0.0

mme_row['Macro Average (%)'] = round((df['MME_Score'].sum() / len(df)) * 100, 1) if len(df) > 0 else 0.0
master_rows.append(mme_row)

# 3. Compile Master DataFrame
master_columns = ['Evaluation Layer', 'Architecture / Method', 'Background Context'] + [f"{e} (%)" for e in emotion_order] + ['Macro Average (%)']
master_df = pd.DataFrame(master_rows)[master_columns]

# Export to target folder location as a tracking CSV
master_csv_path = os.path.join(output_dir, "master_evaluation_matrix_6000.csv")
master_df.to_csv(master_csv_path, index=False)
print(f" ✅ Master Framework Evaluation Matrix saved to CSV:\n 📁 {master_csv_path}\n")

# -------------------------------------------------------------------------
# IMAGE GENERATION: PUBLICATION-READY SUMMARY VISUALIZATION (1000 DPI)
# -------------------------------------------------------------------------
fig_tab, ax_tab = plt.subplots(figsize=(19, 7.5), dpi=1000)
ax_tab.axis('off')
ax_tab.axis('tight')

table_data = master_df.values.tolist()
column_headers = master_df.columns.tolist()

table_obj = ax_tab.table(cellText=table_data, colLabels=column_headers, loc='center', cellLoc='center')

table_obj.auto_set_font_size(False)
table_obj.set_fontsize(10)
table_obj.scale(1.0, 1.8)  # Generous cell padding height

# Apply precise custom column width scaling properties
for (row, col), cell in table_obj.get_celld().items():
    # Base column expansion to ensure structural space
    if col == 0:
        cell.set_width(cell.get_width() * 1.45)
    elif col == 1:
        cell.set_width(cell.get_width() * 1.70)
    elif col == 2:
        cell.set_width(cell.get_width() * 1.15)
    elif col == 10:
        cell.set_width(cell.get_width() * 1.05)

    if row == 0:
        # Title Header Formatting
        cell.set_text_props(weight='bold', color='white', fontsize=10.5)
        cell.set_facecolor('#2c3e50')  # Dark blue header
    else:
        layer_type = table_data[row-1][0]

        # Bold final tracking metrics column
        if col == len(column_headers) - 1:
            cell.set_text_props(weight='bold')

        if layer_type == 'Ensemble System':
            cell.set_facecolor('#ebf5fb')  # Highlight MME layer row
            cell.set_text_props(weight='bold')
        elif layer_type == 'Context Average':
            cell.set_facecolor('#f4f6f7')  # Shading for global background metrics row
            cell.set_text_props(style='italic')
        else:
            cell.set_facecolor('#fcfcfc' if row % 2 == 0 else 'white')  # Soft zebra striping

plt.title("Master Evaluation Framework Matrix: Model × Background Context × Affective Emotion Accuracy Breakdown",
          fontsize=15, fontweight='bold', pad=25, color='#2c3e50')
plt.tight_layout()

master_img_path = os.path.join(output_dir, "master_evaluation_matrix_6000.png")
plt.savefig(master_img_path, dpi=1000, bbox_inches='tight', facecolor='white')
print(f" ✅ Master Evaluation visual matrix saved at 1000 DPI:\n 📁 {master_img_path}")
plt.show()